"""
Django settings for tutorflow project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.management.utils import get_random_secret_key


def env(name: str, default=None):
    """Lightweight environment helper (avoids adding django-environ)."""
    value = os.environ.get(name)
    if value is None:
        return default
    return value


def env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default=None):
    value = os.environ.get(name)
    if value is None:
        return default or []
    # Support comma-separated lists
    return [item.strip() for item in value.split(",") if item.strip()]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Debug log path - works both locally and on Railway
DEBUG_LOG_PATH = Path(__file__).resolve().parent.parent.parent / ".cursor" / "debug.log"
if not DEBUG_LOG_PATH.parent.exists():
    # On Railway, use /app path
    DEBUG_LOG_PATH = Path("/app/.cursor/debug.log")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", default=False)

# SECURITY WARNING: keep the secret key used in production secret!
# #region agent log
try:
    DEBUG_LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(DEBUG_LOG_PATH, "a") as f:
        import json

        f.write(
            json.dumps(
                {
                    "sessionId": "debug-session",
                    "runId": "run1",
                    "hypothesisId": "A",
                    "location": "settings.py:60",
                    "message": "SECRET_KEY check start",
                    "data": {
                        "DEBUG": DEBUG,
                        "SECRET_KEY_set": bool(env("SECRET_KEY")),
                        "code_version": "new",
                    },
                    "timestamp": int(__import__("time").time() * 1000),
                }
            )
            + "\n"
        )
except:  # noqa: E722
    pass
# #endregion
SECRET_KEY = env("SECRET_KEY")
# #region agent log
try:
    with open(DEBUG_LOG_PATH, "a") as f:
        import json

        f.write(
            json.dumps(
                {
                    "sessionId": "debug-session",
                    "runId": "run1",
                    "hypothesisId": "A",
                    "location": "settings.py:63",
                    "message": "After env(SECRET_KEY)",
                    "data": {"SECRET_KEY": bool(SECRET_KEY), "DEBUG": DEBUG},
                    "timestamp": int(__import__("time").time() * 1000),
                }
            )
            + "\n"
        )
except:  # noqa: E722
    pass
# #endregion
if not SECRET_KEY:
    # #region agent log
    try:
        with open(DEBUG_LOG_PATH, "a") as f:
            import json

            f.write(
                json.dumps(
                    {
                        "sessionId": "debug-session",
                        "runId": "run1",
                        "hypothesisId": "B",
                        "location": "settings.py:66",
                        "message": "SECRET_KEY not set, entering if block",
                        "data": {"DEBUG": DEBUG},
                        "timestamp": int(__import__("time").time() * 1000),
                    }
                )
                + "\n"
            )
    except:  # noqa: E722
        pass
    # #endregion
    if DEBUG:
        SECRET_KEY = "dev-insecure-secret-key"
        # #region agent log
        try:
            with open(DEBUG_LOG_PATH, "a") as f:
                import json

                f.write(
                    json.dumps(
                        {
                            "sessionId": "debug-session",
                            "runId": "run1",
                            "hypothesisId": "C",
                            "location": "settings.py:70",
                            "message": "Using dev key",
                            "data": {},
                            "timestamp": int(__import__("time").time() * 1000),
                        }
                    )
                    + "\n"
                )
        except:  # noqa: E722
            pass
        # #endregion
    else:
        # #region agent log
        try:
            with open(DEBUG_LOG_PATH, "a") as f:
                import json

                f.write(
                    json.dumps(
                        {
                            "sessionId": "debug-session",
                            "runId": "run1",
                            "hypothesisId": "D",
                            "location": "settings.py:74",
                            "message": "Production mode, attempting auto-generate",
                            "data": {
                                "get_random_secret_key_available": hasattr(
                                    __import__(
                                        "django.core.management.utils",
                                        fromlist=["get_random_secret_key"],
                                    ),
                                    "get_random_secret_key",
                                )
                            },
                            "timestamp": int(__import__("time").time() * 1000),
                        }
                    )
                    + "\n"
                )
        except Exception as e:
            try:
                with open(DEBUG_LOG_PATH, "a") as f:
                    import json

                    f.write(
                        json.dumps(
                            {
                                "sessionId": "debug-session",
                                "runId": "run1",
                                "hypothesisId": "D",
                                "location": "settings.py:74",
                                "message": "Log error",
                                "data": {"error": str(e)},
                                "timestamp": int(__import__("time").time() * 1000),
                            }
                        )
                        + "\n"
                    )
            except:  # noqa: E722
                pass
        # #endregion
        # Auto-generate SECRET_KEY if not set (fallback for deployment)
        # WARNING: This should be set explicitly in production for security
        try:
            SECRET_KEY = get_random_secret_key()
            # #region agent log
            try:
                with open(DEBUG_LOG_PATH, "a") as f:
                    import json

                    f.write(
                        json.dumps(
                            {
                                "sessionId": "debug-session",
                                "runId": "run1",
                                "hypothesisId": "E",
                                "location": "settings.py:84",
                                "message": "Successfully generated SECRET_KEY",
                                "data": {"SECRET_KEY_length": len(SECRET_KEY)},
                                "timestamp": int(__import__("time").time() * 1000),
                            }
                        )
                        + "\n"
                    )
            except:  # noqa: E722
                pass
            # #endregion
        except Exception as e:
            # #region agent log
            try:
                with open(DEBUG_LOG_PATH, "a") as f:
                    import json

                    f.write(
                        json.dumps(
                            {
                                "sessionId": "debug-session",
                                "runId": "run1",
                                "hypothesisId": "F",
                                "location": "settings.py:90",
                                "message": "Failed to generate SECRET_KEY",
                                "data": {
                                    "error": str(e),
                                    "error_type": type(e).__name__,
                                },
                                "timestamp": int(__import__("time").time() * 1000),
                            }
                        )
                        + "\n"
                    )
            except:  # noqa: E722
                pass
            # #endregion
            raise

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS")
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

if not DEBUG and (not ALLOWED_HOSTS or ALLOWED_HOSTS == ["*"]):
    raise RuntimeError(
        "ALLOWED_HOSTS must be set for production. "
        "Set ALLOWED_HOSTS environment variable with your domain(s), e.g., "
        "ALLOWED_HOSTS=yourdomain.com,www.yourdomain.com or "
        "ALLOWED_HOSTS=*.railway.app",
    )

CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS", default=[])


# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # TutorFlow apps
    "apps.core",
    "apps.students",
    "apps.contracts",
    "apps.lessons",
    "apps.blocked_times",
    "apps.lesson_plans",
    "apps.ai",
    "apps.billing",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "tutorflow.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
            ],
        },
    },
]

WSGI_APPLICATION = "tutorflow.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = env("DATABASE_URL")
# #region agent log
try:
    with open(DEBUG_LOG_PATH, "a") as f:
        import json

        f.write(
            json.dumps(
                {
                    "sessionId": "debug-session",
                    "runId": "run1",
                    "hypothesisId": "G",
                    "location": "settings.py:330",
                    "message": "DATABASE_URL check",
                    "data": {
                        "DATABASE_URL_set": bool(DATABASE_URL),
                        "DATABASE_URL_preview": (
                            DATABASE_URL[:50] + "..."
                            if DATABASE_URL and len(DATABASE_URL) > 50
                            else DATABASE_URL
                        ),
                    },
                    "timestamp": int(__import__("time").time() * 1000),
                }
            )
            + "\n"
        )
except:  # noqa: E722
    pass
# #endregion
if DATABASE_URL:
    # #region agent log
    try:
        parsed_db = dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=False)
        with open(DEBUG_LOG_PATH, "a") as f:
            import json

            f.write(
                json.dumps(
                    {
                        "sessionId": "debug-session",
                        "runId": "run1",
                        "hypothesisId": "H",
                        "location": "settings.py:355",
                        "message": "Parsed DATABASE_URL",
                        "data": {
                            "db_name": parsed_db.get("NAME"),
                            "db_user": parsed_db.get("USER"),
                            "db_host": parsed_db.get("HOST"),
                            "db_port": parsed_db.get("PORT"),
                        },
                        "timestamp": int(__import__("time").time() * 1000),
                    }
                )
                + "\n"
            )
    except Exception as e:
        try:
            with open(DEBUG_LOG_PATH, "a") as f:
                import json

                f.write(
                    json.dumps(
                        {
                            "sessionId": "debug-session",
                            "runId": "run1",
                            "hypothesisId": "H",
                            "location": "settings.py:355",
                            "message": "Failed to parse DATABASE_URL",
                            "data": {"error": str(e)},
                            "timestamp": int(__import__("time").time() * 1000),
                        }
                    )
                    + "\n"
                )
        except:  # noqa: E722
            pass
    # #endregion
    DATABASES = {
        "default": dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=False)
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en"

# Supported languages
LANGUAGES = [
    ("en", "English"),
    ("de", "Deutsch"),
]

# Timezone: Europe/Berlin
TIME_ZONE = "Europe/Berlin"

# Authentication
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"

USE_I18N = True
USE_L10N = True

USE_TZ = True

# Locale paths
LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (User-uploaded files)
# https://docs.djangoproject.com/en/5.2/topics/files/
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", default=False)
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", default=False)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", default=False)


if not DEBUG:
    SECURE_HSTS_SECONDS = int(env("SECURE_HSTS_SECONDS", default="3600"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", default=True)
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# AI/LLM Configuration
# Diese Werte sollten über Umgebungsvariablen gesetzt werden
# Beispiel: export LLM_API_KEY="your-key-here"
LLM_API_BASE_URL = os.environ.get("LLM_API_BASE_URL", "https://api.openai.com/v1")
LLM_API_KEY = os.environ.get("LLM_API_KEY", "")
LLM_MODEL_NAME = os.environ.get("LLM_MODEL_NAME", "gpt-3.5-turbo")
LLM_TIMEOUT_SECONDS = int(os.environ.get("LLM_TIMEOUT_SECONDS", "30"))

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "logs" / "tutorflow.log",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "apps.ai": {
            "handlers": ["console", "file"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
}

# Create logs directory if it doesn't exist
logs_dir = BASE_DIR / "logs"
logs_dir.mkdir(exist_ok=True)
