# Generated by Django 5.2.9 on 2025-12-04 22:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0003_remove_contract_planned_units_per_month'),
        ('lessons', '0008_rename_lesson_to_session_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_name', models.CharField(help_text='Name des Zahlungspflichtigen', max_length=200)),
                ('payer_address', models.TextField(blank=True, help_text='Adresse des Zahlungspflichtigen')),
                ('period_start', models.DateField(help_text='Beginn des Abrechnungszeitraums')),
                ('period_end', models.DateField(help_text='Ende des Abrechnungszeitraums')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('sent', 'Versendet'), ('paid', 'Bezahlt')], default='draft', help_text='Status der Rechnung', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gesamtbetrag der Rechnung', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('document', models.FileField(blank=True, help_text='Generiertes Rechnungsdokument (HTML/PDF)', null=True, upload_to='invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(blank=True, help_text='Zugehöriger Vertrag (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Rechnung',
                'verbose_name_plural': 'Rechnungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Beschreibung des Postens', max_length=500)),
                ('date', models.DateField(help_text='Datum der Unterrichtsstunde (Kopie)')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Dauer in Minuten (Kopie)')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Betrag für diesen Posten', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(help_text='Zugehörige Rechnung', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
                ('lesson', models.ForeignKey(blank=True, help_text='Zugehörige Lesson (kann später gelöscht werden)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='lessons.session')),
            ],
            options={
                'verbose_name': 'Rechnungsposten',
                'verbose_name_plural': 'Rechnungsposten',
                'ordering': ['date', 'description'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='billing_inv_status_541249_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['period_start', 'period_end'], name='billing_inv_period__7aeaa2_idx'),
        ),
    ]
