# Generated by Django 5.2.9 on 2025-12-05 15:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('contracts', '0004_alter_contract_options_and_more'),
        ('lessons', '0008_rename_lesson_to_session_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['date', 'description'], 'verbose_name': 'Invoice Item', 'verbose_name_plural': 'Invoice Items'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Associated contract (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='document',
            field=models.FileField(blank=True, help_text='Generated invoice document (HTML/PDF)', null=True, upload_to='invoices/'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payer_address',
            field=models.TextField(blank=True, help_text='Address of the payer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payer_name',
            field=models.CharField(help_text='Name of the payer', max_length=200),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='period_end',
            field=models.DateField(help_text='Billing period end'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='period_start',
            field=models.DateField(help_text='Billing period start'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid')], default='draft', help_text='Invoice status', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total invoice amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount for this item', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='date',
            field=models.DateField(help_text='Lesson date (copy)'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(help_text='Item description', max_length=500),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='duration_minutes',
            field=models.PositiveIntegerField(help_text='Duration in minutes (copy)'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(help_text='Associated invoice', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Associated lesson (may be deleted later)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='lessons.session'),
        ),
    ]
