# Generated by Django 6.0.2 on 2026-02-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_invoiceitem_lesson_fk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoice',
            new_name='billing_inv_owner_i_b0f32d_idx',
            old_name='billing_inv_owner_i_created_idx',
        ),
    ]
