# Generated by Django 6.0.2 on 2026-02-04 17:36

import apps.billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_rename_billing_inv_owner_i_created_idx_billing_inv_owner_i_b0f32d_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_pdf',
            field=models.FileField(blank=True, help_text='Generated PDF document', null=True, upload_to=apps.billing.models._invoice_pdf_upload_to),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_pdf_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
