# Generated by Django 6.0.2 on 2026-02-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_add_invoice_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When marked as paid', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='When marked as sent', null=True),
        ),
    ]
