# Generated by Django 5.2.9 on 2025-12-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Titel der Blockzeit (z. B. 'Uni-Vorlesung', 'Gemeinde')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Beschreibung der Blockzeit', null=True)),
                ('start_datetime', models.DateTimeField(help_text='Startzeitpunkt')),
                ('end_datetime', models.DateTimeField(help_text='Endzeitpunkt')),
                ('is_recurring', models.BooleanField(default=False, help_text='Ist dies eine wiederkehrende Blockzeit?')),
                ('recurring_pattern', models.CharField(blank=True, help_text="Wiederholungsmuster (z. B. 'weekly', 'daily') - für zukünftige Erweiterung", max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blockzeit',
                'verbose_name_plural': 'Blockzeiten',
                'ordering': ['start_datetime'],
                'indexes': [models.Index(fields=['start_datetime', 'end_datetime'], name='blocked_tim_start_d_5b188b_idx')],
            },
        ),
    ]
