# Generated by Django 5.2.9 on 2025-12-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocked_times', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringBlockedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Titel der Blockzeit (z. B. 'Uni-Vorlesung', 'Gemeinde')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Beschreibung der Blockzeit', null=True)),
                ('start_date', models.DateField(help_text='Startdatum der Serie')),
                ('end_date', models.DateField(blank=True, help_text='Enddatum der Serie (optional)', null=True)),
                ('start_time', models.TimeField(help_text='Startzeit')),
                ('end_time', models.TimeField(help_text='Endzeit')),
                ('recurrence_type', models.CharField(choices=[('weekly', 'Wöchentlich'), ('biweekly', 'Alle 2 Wochen'), ('monthly', 'Monatlich')], default='weekly', help_text='Wiederholungsart: Wöchentlich, alle 2 Wochen oder monatlich', max_length=20)),
                ('monday', models.BooleanField(default=False, help_text='Montag')),
                ('tuesday', models.BooleanField(default=False, help_text='Dienstag')),
                ('wednesday', models.BooleanField(default=False, help_text='Mittwoch')),
                ('thursday', models.BooleanField(default=False, help_text='Donnerstag')),
                ('friday', models.BooleanField(default=False, help_text='Freitag')),
                ('saturday', models.BooleanField(default=False, help_text='Samstag')),
                ('sunday', models.BooleanField(default=False, help_text='Sonntag')),
                ('is_active', models.BooleanField(default=True, help_text='Ist die Serie aktiv?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wiederholende Blockzeit',
                'verbose_name_plural': 'Wiederholende Blockzeiten',
                'ordering': ['-start_date', 'title'],
            },
        ),
    ]
