# Generated by Django 5.2.9 on 2025-12-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocked_times', '0002_recurringblockedtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockedtime',
            options={'ordering': ['start_datetime'], 'verbose_name': 'Blocked Time', 'verbose_name_plural': 'Blocked Times'},
        ),
        migrations.AlterModelOptions(
            name='recurringblockedtime',
            options={'ordering': ['-start_date', 'title'], 'verbose_name': 'Recurring Blocked Time', 'verbose_name_plural': 'Recurring Blocked Times'},
        ),
        migrations.AlterField(
            model_name='blockedtime',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the blocked time', null=True),
        ),
        migrations.AlterField(
            model_name='blockedtime',
            name='end_datetime',
            field=models.DateTimeField(help_text='End datetime'),
        ),
        migrations.AlterField(
            model_name='blockedtime',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Is this a recurring blocked time?'),
        ),
        migrations.AlterField(
            model_name='blockedtime',
            name='recurring_pattern',
            field=models.CharField(blank=True, help_text="Recurrence pattern (e.g., 'weekly', 'daily') - for future extension", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blockedtime',
            name='start_datetime',
            field=models.DateTimeField(help_text='Start datetime'),
        ),
        migrations.AlterField(
            model_name='blockedtime',
            name='title',
            field=models.CharField(help_text="Title of the blocked time (e.g., 'University lecture', 'Community')", max_length=200),
        ),
        migrations.AlterField(
            model_name='recurringblockedtime',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the blocked time', null=True),
        ),
        migrations.AlterField(
            model_name='recurringblockedtime',
            name='end_date',
            field=models.DateField(blank=True, help_text='Series end date (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='recurringblockedtime',
            name='end_time',
            field=models.TimeField(help_text='End time'),
        ),
        migrations.AlterField(
            model_name='recurringblockedtime',
            name='friday',
            field=models.BooleanField(default=False, help_text='Friday'),
        ),
        migrations.AlterField(
            model_name='recurringblockedtime',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the series active?'),
        ),
        migrations.AlterField(
            model_name='recurringblockedtime',
            name='monday',
            field=models.BooleanField(default=False, help_text='Monday'),
        ),
        migrations.AlterField(
            model_name='recurringblockedtime',
            name='recurrence_type',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='weekly', help_text='Recurrence type: Weekly, bi-weekly, or monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='recurringblockedtime',
            name='saturday',
            field=models.BooleanField(default=False, help_text='Saturday'),
        ),
        migrations.AlterField(
            model_name='recurringblockedtime',
            name='start_date',
            field=models.DateField(help_text='Series start date'),
        ),
        migrations.AlterField(
            model_name='recurringblockedtime',
            name='start_time',
            field=models.TimeField(help_text='Start time'),
        ),
        migrations.AlterField(
            model_name='recurringblockedtime',
            name='sunday',
            field=models.BooleanField(default=False, help_text='Sunday'),
        ),
        migrations.AlterField(
            model_name='recurringblockedtime',
            name='thursday',
            field=models.BooleanField(default=False, help_text='Thursday'),
        ),
        migrations.AlterField(
            model_name='recurringblockedtime',
            name='title',
            field=models.CharField(help_text="Title of the blocked time (e.g., 'University lecture', 'Community')", max_length=200),
        ),
        migrations.AlterField(
            model_name='recurringblockedtime',
            name='tuesday',
            field=models.BooleanField(default=False, help_text='Tuesday'),
        ),
        migrations.AlterField(
            model_name='recurringblockedtime',
            name='wednesday',
            field=models.BooleanField(default=False, help_text='Wednesday'),
        ),
    ]
