# Generated by Django 5.2.9 on 2025-12-04 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('school', models.CharField(blank=True, help_text='Name der Schule', max_length=200, null=True)),
                ('grade', models.CharField(blank=True, help_text="Klasse/Stufe (z. B. '10. Klasse', 'Q1')", max_length=50, null=True)),
                ('subjects', models.CharField(blank=True, help_text="Fächer (kommagetrennt, z. B. 'Mathe, Deutsch, Englisch')", max_length=500, null=True)),
                ('notes', models.TextField(blank=True, help_text='Zusätzliche Notizen zum Schüler', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_location', models.ForeignKey(blank=True, help_text='Standard-Unterrichtsort', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='locations.location')),
            ],
            options={
                'verbose_name': 'Schüler',
                'verbose_name_plural': 'Schüler',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
