# Generated by Django 5.2.9 on 2025-12-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, help_text="Grade/Level (e.g., '10th grade', 'Q1')", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the student', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, help_text='School name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.CharField(blank=True, help_text="Subjects (comma-separated, e.g., 'Math, German, English')", max_length=500, null=True),
        ),
    ]
