# Generated by Django 6.0.4 on 2026-05-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0006_add_booking_code_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="student",
            name="grade",
            field=models.CharField(
                blank=True,
                help_text="Grade/Level (e.g., '10th grade', 'Q1')",
                max_length=50,
                null=True,
                verbose_name="grade",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="student",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes about the student",
                null=True,
                verbose_name="notes",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="phone"),
        ),
        migrations.AlterField(
            model_name="student",
            name="school",
            field=models.CharField(
                blank=True,
                help_text="School name",
                max_length=200,
                null=True,
                verbose_name="school",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="subjects",
            field=models.CharField(
                blank=True,
                help_text="Subjects (comma-separated, e.g., 'Math, German, English')",
                max_length=500,
                null=True,
                verbose_name="subjects",
            ),
        ),
    ]
