# Generated by Django 5.2.9 on 2025-12-04 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Thema des Unterrichtsplans', max_length=200)),
                ('subject', models.CharField(help_text="Fach (z. B. 'Mathe', 'Deutsch')", max_length=100)),
                ('content', models.TextField(help_text='KI-generierter Unterrichtsplan (Text)')),
                ('grade_level', models.CharField(blank=True, help_text="Klassenstufe (z. B. '10. Klasse')", max_length=50, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Geplante Dauer in Minuten', null=True)),
                ('llm_model', models.CharField(blank=True, help_text="Verwendetes LLM-Modell (z. B. 'gpt-4', 'claude-3')", max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, help_text='Verknüpfte Unterrichtsstunde (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='lessons.lesson')),
                ('student', models.ForeignKey(help_text='Schüler, für den der Plan erstellt wurde', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='students.student')),
            ],
            options={
                'verbose_name': 'Unterrichtsplan',
                'verbose_name_plural': 'Unterrichtspläne',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='lesson_plan_student_893e49_idx')],
            },
        ),
    ]
