# Generated by Django 5.2.9 on 2025-12-05 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plans', '0001_initial'),
        ('lessons', '0008_rename_lesson_to_session_state'),
        ('students', '0002_alter_student_options_alter_student_grade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonplan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lesson Plan', 'verbose_name_plural': 'Lesson Plans'},
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='content',
            field=models.TextField(help_text='AI-generated lesson plan (text)'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Planned duration in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='grade_level',
            field=models.CharField(blank=True, help_text="Grade level (e.g., '10th grade')", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Associated lesson (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='lessons.session'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='llm_model',
            field=models.CharField(blank=True, help_text="Used LLM model (e.g., 'gpt-4', 'claude-3')", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='student',
            field=models.ForeignKey(help_text='Student for whom the plan was created', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='students.student'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='subject',
            field=models.CharField(help_text="Subject (e.g., 'Math', 'German')", max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='topic',
            field=models.CharField(help_text='Topic of the lesson plan', max_length=200),
        ),
    ]
