# Generated by Django 5.2.9 on 2025-12-04 11:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(blank=True, help_text='Name des Instituts (falls vorhanden)', max_length=200, null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Honorar pro Einheit in Euro', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_duration_minutes', models.PositiveIntegerField(default=60, help_text='Dauer einer Einheit in Minuten')),
                ('start_date', models.DateField(help_text='Vertragsbeginn')),
                ('end_date', models.DateField(blank=True, help_text='Vertragsende (optional, leer = unbefristet)', null=True)),
                ('planned_units_per_month', models.PositiveIntegerField(blank=True, help_text='Geplante Einheiten pro Monat (optional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Ist der Vertrag aktiv?')),
                ('notes', models.TextField(blank=True, help_text='Zusätzliche Notizen zum Vertrag', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(help_text='Schüler, für den der Vertrag gilt', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='students.student')),
            ],
            options={
                'verbose_name': 'Vertrag',
                'verbose_name_plural': 'Verträge',
                'ordering': ['-start_date', 'student'],
            },
        ),
    ]
