# Generated by Django 5.2.9 on 2025-12-04 16:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='planned_units_per_month',
            field=models.PositiveIntegerField(blank=True, help_text='Geplante Einheiten pro Monat (optional, deprecated - use ContractMonthlyPlan)', null=True),
        ),
        migrations.CreateModel(
            name='ContractMonthlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Jahr')),
                ('month', models.PositiveIntegerField(help_text='Monat (1-12)', validators=[django.core.validators.MinValueValidator(1)])),
                ('planned_units', models.PositiveIntegerField(default=0, help_text='Geplante Einheiten für diesen Monat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(help_text='Zugehöriger Vertrag', on_delete=django.db.models.deletion.CASCADE, related_name='monthly_plans', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Monatlicher Vertragsplan',
                'verbose_name_plural': 'Monatliche Vertragspläne',
                'ordering': ['year', 'month'],
                'unique_together': {('contract', 'year', 'month')},
            },
        ),
    ]
