# Generated by Django 5.2.9 on 2025-12-04 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contract_planned_units_per_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='planned_units_per_month',
        ),
    ]
