# Generated by Django 5.2.9 on 2025-12-05 15:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_remove_contract_planned_units_per_month'),
        ('students', '0002_alter_student_options_alter_student_grade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-start_date', 'student'], 'verbose_name': 'Contract', 'verbose_name_plural': 'Contracts'},
        ),
        migrations.AlterModelOptions(
            name='contractmonthlyplan',
            options={'ordering': ['year', 'month'], 'verbose_name': 'Contract Monthly Plan', 'verbose_name_plural': 'Contract Monthly Plans'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, help_text='Contract end date (optional, empty = unlimited)', null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, help_text='Rate per unit in EUR', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='institute',
            field=models.CharField(blank=True, help_text='Institute name (if applicable)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the contract active?'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the contract', null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(help_text='Contract start date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='student',
            field=models.ForeignKey(help_text='Student for whom the contract applies', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='students.student'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='unit_duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Duration of one unit in minutes'),
        ),
        migrations.AlterField(
            model_name='contractmonthlyplan',
            name='contract',
            field=models.ForeignKey(help_text='Associated contract', on_delete=django.db.models.deletion.CASCADE, related_name='monthly_plans', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='contractmonthlyplan',
            name='month',
            field=models.PositiveIntegerField(help_text='Month (1-12)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='contractmonthlyplan',
            name='planned_units',
            field=models.PositiveIntegerField(default=0, help_text='Planned units for this month'),
        ),
        migrations.AlterField(
            model_name='contractmonthlyplan',
            name='year',
            field=models.PositiveIntegerField(help_text='Year'),
        ),
    ]
