# Generated by Django 6.0 on 2026-01-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='has_monthly_planning_limit',
            field=models.BooleanField(default=True, help_text='If checked, monthly planning with planned units is required. If unchecked, no maximum number of units is planned.'),
        ),
    ]
