# Generated by Django 6.0.4 on 2026-05-29 21:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0007_contractmonthlyplan_unique_constraint"),
        ("students", "0007_institutetierconfig"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Contract end date (optional, empty = unlimited)",
                null=True,
                verbose_name="end date",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="has_monthly_planning_limit",
            field=models.BooleanField(
                default=True,
                help_text="If checked, monthly planning with planned units is required. If unchecked, no maximum number of units is planned.",
                verbose_name="monthly planning limit",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="hourly_rate",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Rate per unit in EUR",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="hourly rate",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="institute",
            field=models.CharField(
                blank=True,
                help_text="Institute name (if applicable)",
                max_length=200,
                null=True,
                verbose_name="institute",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Is the contract active?", verbose_name="active"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes about the contract",
                null=True,
                verbose_name="notes",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="start_date",
            field=models.DateField(help_text="Contract start date", verbose_name="start date"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="student",
            field=models.ForeignKey(
                help_text="Student for whom the contract applies",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="students.student",
                verbose_name="student",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="unit_duration_minutes",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Duration of one unit in minutes",
                verbose_name="unit duration (minutes)",
            ),
        ),
        migrations.CreateModel(
            name="InstituteTierConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("institute_name", models.CharField(max_length=200, verbose_name="institute name")),
                (
                    "tiers",
                    models.JSONField(
                        default=list,
                        help_text='List of dicts: [{"hours_from": 0, "label": "13 €/h"}, ...], sorted by hours_from ascending',
                        verbose_name="tiers",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institute_tier_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Institute tier config",
                "verbose_name_plural": "Institute tier configs",
                "ordering": ["institute_name"],
                "unique_together": {("user", "institute_name")},
            },
        ),
    ]
