# Generated by Django 5.2.9 on 2025-12-04 11:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Datum der Unterrichtsstunde')),
                ('start_time', models.TimeField(help_text='Startzeit')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Dauer in Minuten', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('planned', 'Geplant'), ('taught', 'Unterrichtet'), ('cancelled', 'Ausgefallen'), ('paid', 'Ausgezahlt')], default='planned', help_text='Status der Unterrichtsstunde', max_length=20)),
                ('travel_time_before_minutes', models.PositiveIntegerField(default=0, help_text='Fahrtzeit vorher in Minuten')),
                ('travel_time_after_minutes', models.PositiveIntegerField(default=0, help_text='Fahrtzeit nachher in Minuten')),
                ('notes', models.TextField(blank=True, help_text='Notizen zur Unterrichtsstunde', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(help_text='Zugehöriger Vertrag', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Unterrichtsstunde',
                'verbose_name_plural': 'Unterrichtsstunden',
                'ordering': ['-date', '-start_time'],
                'indexes': [models.Index(fields=['date', 'start_time'], name='lessons_les_date_e38248_idx'), models.Index(fields=['status'], name='lessons_les_status_ff86f9_idx')],
            },
        ),
    ]
