# Generated by Django 5.2.9 on 2025-12-04 18:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_remove_contract_planned_units_per_month'),
        ('lessons', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Startdatum der Serie')),
                ('end_date', models.DateField(blank=True, help_text='Enddatum der Serie (optional, leer = bis Vertragsende)', null=True)),
                ('start_time', models.TimeField(help_text='Startzeit')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Dauer in Minuten', validators=[django.core.validators.MinValueValidator(1)])),
                ('travel_time_before_minutes', models.PositiveIntegerField(default=0, help_text='Fahrtzeit vorher in Minuten')),
                ('travel_time_after_minutes', models.PositiveIntegerField(default=0, help_text='Fahrtzeit nachher in Minuten')),
                ('monday', models.BooleanField(default=False, help_text='Montag')),
                ('tuesday', models.BooleanField(default=False, help_text='Dienstag')),
                ('wednesday', models.BooleanField(default=False, help_text='Mittwoch')),
                ('thursday', models.BooleanField(default=False, help_text='Donnerstag')),
                ('friday', models.BooleanField(default=False, help_text='Freitag')),
                ('saturday', models.BooleanField(default=False, help_text='Samstag')),
                ('sunday', models.BooleanField(default=False, help_text='Sonntag')),
                ('is_active', models.BooleanField(default=True, help_text='Ist die Serie aktiv?')),
                ('notes', models.TextField(blank=True, help_text='Notizen zur Serie', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(help_text='Zugehöriger Vertrag', on_delete=django.db.models.deletion.CASCADE, related_name='recurring_lessons', to='contracts.contract')),
                ('location', models.ForeignKey(blank=True, help_text='Ort der Unterrichtsstunde (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_lessons', to='locations.location')),
            ],
            options={
                'verbose_name': 'Wiederholende Unterrichtsstunde',
                'verbose_name_plural': 'Wiederholende Unterrichtsstunden',
                'ordering': ['-start_date', 'contract'],
            },
        ),
    ]
