# Generated by Django 5.2.9 on 2025-12-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_recurringlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringlesson',
            name='recurrence_type',
            field=models.CharField(choices=[('weekly', 'Wöchentlich'), ('biweekly', 'Alle 2 Wochen'), ('monthly', 'Monatlich')], default='weekly', help_text='Wiederholungsart: Wöchentlich, alle 2 Wochen oder monatlich', max_length=20),
        ),
    ]
