# Generated by Django 5.2.9 on 2025-12-05 15:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contract_options_and_more'),
        ('lessons', '0003_recurringlesson_recurrence_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-date', '-start_time'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='recurringlesson',
            options={'ordering': ['-start_date', 'contract'], 'verbose_name': 'Recurring Lesson', 'verbose_name_plural': 'Recurring Lessons'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='contract',
            field=models.ForeignKey(help_text='Associated contract', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(help_text='Lesson date'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes for the lesson', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_time',
            field=models.TimeField(help_text='Start time'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('taught', 'Taught'), ('cancelled', 'Cancelled'), ('paid', 'Paid')], default='planned', help_text='Lesson status', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='travel_time_after_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Travel time after in minutes'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='travel_time_before_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Travel time before in minutes'),
        ),
        migrations.AlterField(
            model_name='recurringlesson',
            name='contract',
            field=models.ForeignKey(help_text='Associated contract', on_delete=django.db.models.deletion.CASCADE, related_name='recurring_lessons', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='recurringlesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='recurringlesson',
            name='end_date',
            field=models.DateField(blank=True, help_text='Series end date (optional, empty = until contract end)', null=True),
        ),
        migrations.AlterField(
            model_name='recurringlesson',
            name='friday',
            field=models.BooleanField(default=False, help_text='Friday'),
        ),
        migrations.AlterField(
            model_name='recurringlesson',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the series active?'),
        ),
        migrations.AlterField(
            model_name='recurringlesson',
            name='monday',
            field=models.BooleanField(default=False, help_text='Monday'),
        ),
        migrations.AlterField(
            model_name='recurringlesson',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes for the series', null=True),
        ),
        migrations.AlterField(
            model_name='recurringlesson',
            name='recurrence_type',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='weekly', help_text='Recurrence type: Weekly, bi-weekly, or monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='recurringlesson',
            name='saturday',
            field=models.BooleanField(default=False, help_text='Saturday'),
        ),
        migrations.AlterField(
            model_name='recurringlesson',
            name='start_date',
            field=models.DateField(help_text='Series start date'),
        ),
        migrations.AlterField(
            model_name='recurringlesson',
            name='start_time',
            field=models.TimeField(help_text='Start time'),
        ),
        migrations.AlterField(
            model_name='recurringlesson',
            name='sunday',
            field=models.BooleanField(default=False, help_text='Sunday'),
        ),
        migrations.AlterField(
            model_name='recurringlesson',
            name='thursday',
            field=models.BooleanField(default=False, help_text='Thursday'),
        ),
        migrations.AlterField(
            model_name='recurringlesson',
            name='travel_time_after_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Travel time after in minutes'),
        ),
        migrations.AlterField(
            model_name='recurringlesson',
            name='travel_time_before_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Travel time before in minutes'),
        ),
        migrations.AlterField(
            model_name='recurringlesson',
            name='tuesday',
            field=models.BooleanField(default=False, help_text='Tuesday'),
        ),
        migrations.AlterField(
            model_name='recurringlesson',
            name='wednesday',
            field=models.BooleanField(default=False, help_text='Wednesday'),
        ),
    ]
