# Generated by Django 6.0 on 2026-01-25 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lesson_options_alter_recurringlesson_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Document file', upload_to='lesson_documents/')),
                ('name', models.CharField(blank=True, help_text='Optional name/description for the document', max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Upload timestamp')),
                ('lesson', models.ForeignKey(help_text='Associated lesson', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Lesson Document',
                'verbose_name_plural': 'Lesson Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
