# Generated by Django 6.0.2 on 2026-02-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_rename_lesson_to_session_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringsession',
            options={'ordering': ['-start_date', 'contract'], 'verbose_name': 'Recurring Session', 'verbose_name_plural': 'Recurring Sessions'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-date', '-start_time'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterModelOptions(
            name='sessiondocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Session Document', 'verbose_name_plural': 'Session Documents'},
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(help_text='Session date'),
        ),
        migrations.AlterField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes for the session', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('taught', 'Taught'), ('cancelled', 'Cancelled'), ('paid', 'Paid')], default='planned', help_text='Session status', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessiondocument',
            name='file',
            field=models.FileField(help_text='Document file', upload_to='session_documents/'),
        ),
    ]
